export const SCOPE = process.env.SCOPE;
export const CLIENT_ID = process.env.CLIENT_ID;
export const ENVIRONMENT = process.env.ENVIRONMENT || 'DEV';
export const AUTHORIZATION_KEY = process.env.AUTHORIZATION_KEY || '';
export const AUD = process.env.AUD;
export const AUTH_DOMAIN = process.env.AUTH_DOMAIN || 'authenticatie.vlaanderen.be';
export const API_BASE = process.env.API_URL || 'https://iv.api.vlaanderen.be/api/v1/organisaties/verenigingen/';
export const API_VERSION = process.env.API_VERSION || 'v1';
export const EDITOR_ROLE = 'verenigingen-beheerder';
export const HEADER_MU_SESSION_ID = 'mu-session-id';
export const MU_REQUEST_HEADERS = ['mu-session-id', 'mu-auth-allowed-groups'];
export const ORGANISATION_GRAPH = process.env.ORGANISATION_GRAPH || 'http://mu.semte.ch/graphs/public';
export const SESSION_GRAPH = process.env.SESSION_GRAPH || 'http://mu.semte.ch/graphs/sessions';
export const PROCESSING_AGREEMENT_GRAPH = process.env.PROCESSING_AGREEMENT_GRAPH || 'http://mu.semte.ch/graphs/processing-agreements';
export const CLIENT_CONFIG_GRAPH = process.env.CLIENT_CONFIG_GRAPH || 'http://mu.semte.ch/graphs/client-configurations';
export const ENABLE_PROCESSING_AGREEMENT_CHECK = process.env.ENABLE_PROCESSING_AGREEMENT_CHECK !== 'false';
